In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model

%matplotlib inline

In [2]:
# we are loading our data in a "data" variable.
data = pd.read_csv("data/data.csv")

# from all the data we are just selecting "ITIN_YIELD" and "DISTANCE" column to use and saving these columns to "source_data"
source_data = data[['ITIN_YIELD', 'DISTANCE']]

# from those two column we are trying to predict "ITIN_FARE" column. So we are also saving the column in "predicted_column" variable
predicted_column = data['ITIN_FARE']

# with this line we are just showing first 5 line of our all data
data.head()

,ITIN_ID,COUPONS,YEAR,QUARTER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_COUNTRY,ORIGIN_STATE_FIPS,...,ITIN_YIELD,REPORTING_CARRIER,PASSENGERS,ITIN_FARE,BULK_FARE,DISTANCE,DISTANCE_GROUP,MILES_FLOWN,ITIN_GEO_TYPE,Unnamed: 25
0,201719,1,2017,1,ABE,10135,1013503,30135,US,42,...,0.5482,9E,1.0,233.0,0.0,425.0,1,425.0,2,NaN
1,2017110,1,2017,1,ABE,10135,1013503,30135,US,42,...,0.8447,9E,1.0,359.0,0.0,425.0,1,425.0,2,NaN
2,2017111,1,2017,1,ABE,10135,1013503,30135,US,42,...,0.9153,9E,1.0,389.0,0.0,425.0,1,425.0,2,NaN
3,2017112,2,2017,1,ABE,10135,1013503,30135,US,42,...,0.2306,9E,1.0,196.0,0.0,850.0,2,850.0,2,NaN
4,2017113,2,2017,1,ABE,10135,1013503,30135,US,42,...,0.2306,9E,1.0,196.0,0.0,850.0,2,850.0,2,NaN

In [ ]:
# inside the "train_test_split()" we are providing our data. And populating our X_train, Y_train, X_test and Y_test variables
# X_train variable contains the data of  our training "source_data" 
# X_test variable contains the data of  our testing "sourse_data"
# Y_train variable contains the data of  our training "predicted_column"
# Y_test variable contains the data of  our testing "predicted_column"

X_train, X_test, y_train, y_test = train_test_split(source_data, predicted_column, random_state=42)


# we are loading our algorithm in "forest" variable
logreg = linear_model.LogisticRegression(C=1e5)

# we are telling our algorithm to train from our training dataset
logreg.fit(X_train, y_train)

In [ ]:
# Now we are trying to predict our estimated fare from by giving our algorithm some value. And we can see that, its trying to predict.

X_new = np.array([[0.2306, 850.0]])
prediction = logreg.predict(X_new)
print("Prediction: {}".format(prediction))

In [ ]:
# Now we are giving our algorithm our test data set. So that, it can try to predict the values of test data also.

y_pred = logreg.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

In [ ]:
# Here are we are trying to watch our prediction score. How much it can learn from our training and testing data.

print("Accuracy on training set: {:.3f}".format(logreg.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(logreg.score(X_test, y_test)))